### ISSUE TITLE
java foolnltk环境问题

### ISSUE THREAD

**Issue by Derekkk** [rockyzhengwu/JFoolNLTK#1]
请问是不是只支持linux或者mac os，我在windows下运行得到报错：
“Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: windows, architecture: x86.”

**Comment by rockyzhengwu** [comment]
@Derekkk 　我在linux 下开发的，Tensorflow 在windows Java 版我还没测过
你可以参考下这个: https://stackoverflow.com/questions/42350009/native-library-for-tensorflow-java-on-windows

**Comment by Derekkk** [comment]
@rockyzhengwu 感谢回复，我在mac os上测试了一下没有问题，估计是tf for java环境的问题。
