### ISSUE TITLE
JAVA版里怎么调用自己训练的模型呢

### ISSUE THREAD

**Issue by zhishan332** [rockyzhengwu/JFoolNLTK#3]
请教一下，
这个类me.midday.FoolNLTK应该是入口类，但是里面没有能加载自己训练的模型的方法。
我看了下me.midday.lexical.LSTMLexicalAnalyzer想通过这个类实现，但是发现在Python中使用的是maps.pkl，但是java里用的是all_map.json，它们之间怎么转换呢？
谢谢！

**Comment by rockyzhengwu** [comment]
用Python 把maps.pkl 写成all_map.json 的json 格式就好了

**Comment by zhishan332** [comment]
了解了，谢谢
